### ISSUE TITLE
Show realtime enabled/disabled

### ISSUE THREAD

**Issue by awalias** [supabase/grid#10]
on the table view need to show whether realtime is enabled or not for a table

and make sure we don't .subscribe() if realtime disabled for table

**Comment by MildTomato** [comment]
should this be in @supabase/infrastructure ?

**Comment by i-pip** [comment]
I'd like to implement this please, just a couple of questions though. 
1. When ran on my machine this grid by default is not editable - so this results in the grid been generated from the OpenApi description (which lacks the `rls_enabled` field - required for determining if table has realtime enabled) 
2. At what point are the UDF's in [Functions.md](https://github.com/supabase/grid/blob/develop/FUNCTIONS.md) created? I created a dummy project and queried all the UDFs in the prod DB and didn't find them, also tried to just call them in the SQL console and no joy there either. 
3. Are the UDF's implemented or is this a todo? If so (with a little guidance) I'd love to help. 
3. Is there a Slack or Discord I can join where these questions would be more appropriate? 
> Man I so badly wanna come work with y'all - truly incredible team you've got here (genuine awe from walking through the source code - I've been low-key camping in your repos the past couple of weeks - video coming soon)

**Comment by phamhieu** [comment]
Hi @i-pip, this issue is related to our dashboard app. Its in the wrong repo. I will move it.

The grid doesn't have enough access to pull table realtime status
