### ISSUE TITLE
Updating a boolean value in table view not working

### ISSUE THREAD

**Issue by thorwebdev** [supabase/grid#100]
# Bug report

## Describe the bug

Updating a boolean value via the checkbox in the table view isn't working.

## To Reproduce

see video

## Screenshots

https://user-images.githubusercontent.com/5748289/144220989-a0636c95-8597-4c60-a39d-067a8d576b4b.mov

## System information

- OS: MacBook Air (M1, 2020), macOS Big Sur 11.6.1 (20G224)
- Browser: Version 96.0.4664.55 (Official Build) (arm64)

**Comment by phamhieu** [comment]
@thorwebdev can you add my email (phamhieu1998@gmail.com) to the project organisation team to debug. Thank you
