### ISSUE TITLE
export all rows - only exports visible rows. - is there a way to get all of them?

### ISSUE THREAD

**Issue by johndpope** [supabase/grid#101]
# Bug report

## Describe the bug

I get 146 rows at bottom - I click export all rows 
![Screen Shot 2021-12-07 at 21 55 21](https://user-images.githubusercontent.com/289994/145016856-e392e35a-0db7-4f83-b03e-2cf1e15c06c0.png)
<img width="1085" alt="Screen Shot 2021-12-07 at 21 57 04" src="https://user-images.githubusercontent.com/289994/145017021-bf3604dd-7a1f-4c5d-ae34-44886cef6eb5.png">

it only returns 101

![Screen Shot 2021-12-07 at 21 58 45](https://user-images.githubusercontent.com/289994/145017088-6258a5d1-001d-4beb-b58d-aa9d2c56c010.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by johndpope** [comment]
I looked at this - and while the exporting is sympathetic to the grid - I don't need it - just want the csv to export......

I  need to upgrade this function


```


  function onRowsExportCsv() {
    const rows = allRows.filter((x) => selectedRows.has(x.idx));
    const csv = exportRowsToCsv(state.table!.columns, rows);
    const csvData = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    FileSaver.saveAs(csvData, `${state.table!.name}_rows.csv`);
  }
```


When we use grid - I can see  in onSqlQuerythe limit imposed to 100.
<SupabaseGrid
            onSqlQuery={async (query: string) => {
              //   query = "select * from public.transactions where account_id = 258 order by id asc nulls last limit 100 offset 0; "
              // }
              const res = await postAndWait('/api/sql-query', { query });
              console.log("res:", res);
              return res;
            }}

My question is 

export function exportRowsToCsv(
  columns: SupaColumn[],
  rows: SupaRow[],
  separator: string = ','
) 


How do I get my json response to parse into the SupaColumn and SupaRow.....
It's not so trivial....

I don't mind running the metaquery on the table to get column names (independent of the grid) - but how do I turn the json data into the SupaRow format (so that I can cherry pick the export csv function)?
```typescript

  const exportCsv = () => {
    const query = `select * from public.transactions where account_id = ${props.account.id} order by id asc nulls last offset 0;`
    
    const allRows = postAndWait('/api/sql-query', { query });
    console.log("allRows:", allRows);

   // ME - allRows -> allSupaRows - how to do this???

    const csv = exportRowsToCsv(state.table!.columns, rows);
    const csvData = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    FileSaver.saveAs(csvData, `${state.table!.name}_rows.csv`);
  }
```

**Comment by phamhieu** [comment]
Hi @johndpope 

- If your table has less than 1000 rows, you can change the total rows per page and export. 

![Screenshot 2021-12-17 at 12 27 35 PM](https://user-images.githubusercontent.com/689843/146493834-be9dbc0b-bfe8-4b0d-98c3-be285a6d376a.png)

- if your table has more than 1000 rows, you can try to use SQL editor. I believe it can support up to 10000 rows. 
- If you need more than that then you need to use a native postgresql client

**Comment by johndpope** [comment]
thanks

**Comment by johndpope** [comment]
@phamhieu - the way I’m using this control / I am clicking links and going to  a new screen. Is there any easy way I can clear any saved preference / filters when I build the grid?
