### ISSUE TITLE
Run example - "connection pool has ended"

### ISSUE THREAD

**Issue by jjromary** [supabase/grid#139]
# Bug report

## Describe the bug
I followed the steps to be able to run the example and test the grid, but the connection is not kept online.

The sample application is unable to stay connected to Supabase. The environment variable is correctly configured in .env, but as soon as the application tries to fetch the data from Supabase, this message appears in the log "connection pool has ended".

## To Reproduce

1. Go to "Run example" in Read.me and follow steps
2. Access your project at subase.com>settings>Database. Look for the Connection string block. 
3. Copy your string and paste it in the environment variable NEXT_PUBLIC_CONNECTION_STRING
4. Run the application and see the error in the terminal

## Expected behavior
The application is expected to remain Online

## Screenshots
![pool has ended](https://user-images.githubusercontent.com/37199044/171511635-3a62b626-45d0-4ae5-bed9-b72f5387f6e6.png)
![loading infinite](https://user-images.githubusercontent.com/37199044/171511703-a7986058-346f-4d4e-ac20-071c3e58a22e.png)

## System information

- OS: [ Windows10]
- Browser [ chrome]
- Version of supabase/grid: [e.g. 2.0.0]
- Version of Node.js: [e.g. 14.19.3]

**Comment by phamhieu** [comment]
> I followed the steps to be able to run the example and test the grid, but the connection is not kept online.
That's expected for the example app @jjromary cos i end the connection pool on each query
https://github.com/supabase/grid/blob/7bc0b11c1c6d49550b88cccee338e5751b01dbd3/example/pages/api/sql-query.ts#L17-L21

https://github.com/supabase/grid/blob/7bc0b11c1c6d49550b88cccee338e5751b01dbd3/example/components/grid.tsx#L7-L8
if you can't see your table data, try to change default schema and tableName to an existing table in your db

**Comment by jjromary** [comment]
Thanks for the explanation @phamhieu , I was able to visualize the data of my table.

**Comment by jjromary** [comment]
> > I followed the steps to be able to run the example and test the grid, but the connection is not kept online.
> 
> That's expected for the example app @jjromary cos i end the connection pool on each query
> 
> https://github.com/supabase/grid/blob/7bc0b11c1c6d49550b88cccee338e5751b01dbd3/example/pages/api/sql-query.ts#L17-L21
> 
> https://github.com/supabase/grid/blob/7bc0b11c1c6d49550b88cccee338e5751b01dbd3/example/components/grid.tsx#L7-L8
> 
> 
> if you can't see your table data, try to change default schema and tableName to an existing table in your db

Thanks for the explanation @phamhieu , I was able to visualize the data of my table.
