### ISSUE TITLE
clicking to enter new value in text cell shows [null]

### ISSUE THREAD

**Issue by awalias** [supabase/grid#14]
1. have existing rows
2. add a new text column
3. click one to edit
4. see [null] (expected to see empty cell with cursor)

<img width="562" alt="image" src="https://user-images.githubusercontent.com/458736/119255689-bbf67080-bbef-11eb-831c-54b6d04f0c0c.png">

**Comment by phamhieu** [comment]
fixed:
- Show [null] as row value
- Click/Enter will show empty editor for user input

<img width="416" alt="Screenshot 2021-06-01 at 11 48 46 AM" src="https://user-images.githubusercontent.com/689843/120268086-66952000-c2cf-11eb-8614-63464885ca00.png">
<img width="420" alt="Screenshot 2021-06-01 at 11 48 52 AM" src="https://user-images.githubusercontent.com/689843/120268093-69901080-c2cf-11eb-8a3c-45064791f0cb.png">
