### ISSUE TITLE
Delete (cmd + delete) not working

### ISSUE THREAD

**Issue by kiwicopple** [supabase/grid#24]
Possible regression:

![image](https://user-images.githubusercontent.com/10214025/120128327-53615200-c1f4-11eb-8615-23332670a04d.png)

https://supabase.slack.com/archives/CSMGA08FP/p1622343866081800
https://supabase.slack.com/archives/CSMGA08FP/p1622403490082400

**Comment by phamhieu** [comment]
fixed: https://github.com/supabase/grid/commit/9e329cc5bdb12b06e3a2fd9cc20b79336b0d3586

**Comment by phamhieu** [comment]
There're issues with delete row shortcut:
- it depend on row index which will change after a deletion
- it's dangerous

I will remove this shortcut. We will bring back row context menu. Hope it's good enough.
