### ISSUE TITLE
Add Delete button

### ISSUE THREAD

**Issue by kiwicopple** [supabase/grid#25]
Regression:

> Before the most recent update, I could select some rows and then there was a menu to delete all selected. I've looked around and do not see that menu or a delete button now. What am I missing?
> Thank you for the help!

https://supabase.slack.com/archives/CSMGA08FP/p1622407764082500

> Why can't we delete table rows anymore? This action was available in the previous version.

https://supabase.slack.com/archives/CSMGA08FP/p1622412256082800

We need to make the delete button a bit clearer

**Comment by awalias** [comment]
I also can't find the delete button

**Comment by awalias** [comment]
![image](https://user-images.githubusercontent.com/458736/120254277-0e085780-c2bc-11eb-8e45-60742f09e08e.png)

I think this one quite urgent

**Comment by phamhieu** [comment]
there are 2 options to delete row:

- dropdown box from the arrow button like column editing
<img width="278" alt="Screenshot 2021-06-03 at 10 08 54 AM" src="https://user-images.githubusercontent.com/689843/120580690-d207fa80-c453-11eb-8e3f-106f0e6a6fd3.png">

- right click to delete a row
<img width="311" alt="Screenshot 2021-06-03 at 10 08 44 AM" src="https://user-images.githubusercontent.com/689843/120580702-d46a5480-c453-11eb-88b6-488df92f797e.png">
