### ISSUE TITLE
Cannot edit float8/varchar cells

### ISSUE THREAD

**Issue by awalias** [supabase/grid#26]
cannot edit float8 cells in grid:

![image](https://user-images.githubusercontent.com/458736/120150043-22e1de00-c21d-11eb-9519-449a56b13021.png)

**Comment by awalias** [comment]
same for VARCHAR

![image](https://user-images.githubusercontent.com/458736/120150941-40637780-c21e-11eb-9c9b-4a4e1949680b.png)

**Comment by MildTomato** [comment]
#feedback channel reporting same issue
https://supabase.slack.com/archives/CSMGA08FP/p1622443308086700

**Comment by phamhieu** [comment]
yeah, already fixed
