### ISSUE TITLE
Error trying to select FK for new row

### ISSUE THREAD

**Issue by awalias** [supabase/grid#27]
clicking this:
![image](https://user-images.githubusercontent.com/458736/120151844-56256c80-c21f-11eb-97f6-bb9ab5e1c22b.png)

gives: 
![image](https://user-images.githubusercontent.com/458736/120151926-748b6800-c21f-11eb-9bdf-491ab59ef3a0.png)

full screencap

![image](https://user-images.githubusercontent.com/458736/120151731-32fabd00-c21f-11eb-8923-8ecfcda250a5.png)

**Comment by phamhieu** [comment]
move to dashboard repo https://github.com/supabase/infrastructure/issues/1154
