### ISSUE TITLE
Query fails in UI when more than 1,000 rows returned

### ISSUE THREAD

**Issue by justinkelly** [supabase/grid#39]
# Bug report

When using the Supabase SQL editor - and the query returns 1,000 or more rows - The editor returns "An error has occured: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

![image](https://user-images.githubusercontent.com/249520/120923358-7cf90c80-c711-11eb-88e8-90c5f263a7a7.png)

## Describe the bug

When using the Supabase SQL editor - and the query returns 1,000 or more rows - The editor returns "An error has occured: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

![image](https://user-images.githubusercontent.com/249520/120923358-7cf90c80-c711-11eb-88e8-90c5f263a7a7.png)

When using the postgres client - on queries with 1,000 or more results - postgres produces a promt
The result set has more than 1000 rows.
Do you want to continue? [y/N]: y
+------------------------------------

![image](https://user-images.githubusercontent.com/249520/120923397-a6b23380-c711-11eb-9d68-fe433acb0981.png)

This prompt appears to cause the Supabase sql editor to fail

## To Reproduce

In Supabase SQL editor - do a query that will return 1000 or more results
It will fail

## Expected behavior
The postgres prompt is displayed - and user can decide to continue or now

## Screenshots

![image](https://user-images.githubusercontent.com/249520/120923358-7cf90c80-c711-11eb-88e8-90c5f263a7a7.png)

![image](https://user-images.githubusercontent.com/249520/120923397-a6b23380-c711-11eb-9d68-fe433acb0981.png)

## Additional context

Hopefully this is the correct repo for this bug - if its not please let me know the correct one and i'll file it there

**Comment by phamhieu** [comment]
Thanks @justinkelly, I will pass this issue to the team.

**Comment by phamhieu** [comment]
Moved to https://github.com/supabase/infrastructure/issues/1162

**Comment by justinkelly** [comment]
Thanks @phamhieu - appreciated!! Kepp up the great work and looking forward to seeing functions in Supabase

**Comment by phamhieu** [comment]
@justinkelly, I can't replicate your issue. I can confirm that SQL editor has no maximum record settings. 

Maybe your query response is too big and the request gets timeout (we definitely improve the UI to show a proper timeout message). 
If you have more details which can help to reproduce the bug, feel free to open a new issue at https://github.com/supabase/supabase.
