### ISSUE TITLE
Copy cell content action on row contextMenu

### ISSUE THREAD

**Issue by phamhieu** [supabase/grid#41]
# Feature request

## Is your feature request related to a problem? Please describe.

> Sorry. Last one today. It would be nice if when you right clicked on a cell you could copy its contents rather than have to open up the panel and do it from there. It's not intuitive having to right click, edit. I first tried clicking the external link icon, which opens a modal showing its relationship, but clicking on the UUID to copy the data would actually close the modal itself. That feels like a bug?
pcampbell0@gmail.com
/project/lgextaxefbwdovkzriju/editor/table

## Describe the solution you'd like

Add in another action on this menu:
- Copy cell content

<img width="374" alt="Screenshot 2021-06-07 at 9 56 42 AM" src="https://user-images.githubusercontent.com/689843/120953187-ae57f380-c776-11eb-8244-3b6be65734d5.png">

**Comment by ankitjena** [comment]
Hey @phamhieu , I would like to work on this. I had a stupid question though, which port does the server run on doing `npm start`

**Comment by ankitjena** [comment]
@phamhieu @MildTomato I seem to be getting 404s in the requests which fetch table data, I pasted the url and anon key, is there something I am doing wrong?

**Comment by phamhieu** [comment]
@ankitjena Have you created `Postgresql functions` so that it can pull your table info?

https://github.com/supabase/grid/blob/develop/FUNCTIONS.md

OR you can try to show readonly table from the example which doesn't required `Postgresql functions`
