### ISSUE TITLE
Text columns with null values are rendered incorrectly

### ISSUE THREAD

**Issue by inian** [supabase/grid#42]
I tried creating a table with a text column and in rows where the column value is null, it shows up as `[null]`. The array notation makes it weird. 

![image](https://user-images.githubusercontent.com/2155545/120968511-8a5ad900-c79b-11eb-9821-ea2ad15fa51b.png)

This is how TablePlus does it. The faded colors for NULL also looks nice
![image](https://user-images.githubusercontent.com/2155545/120968565-9c3c7c00-c79b-11eb-9f0f-8b220a280f16.png)

It also differentiates between NULL and EMPTY but once I import this into our database via a CSV import, both NULL and EMPTY show as `[null]`

**Comment by phamhieu** [comment]
> This is how TablePlus does it. The faded colors for NULL also looks nice

yeah, good suggestion. What do you think @MildTomato?

> It also differentiates between NULL and EMPTY but once I import this into our database via a CSV import, both NULL and EMPTY show as [null]

I will check this issue. thanks @inian

**Comment by MildTomato** [comment]
>yeah, good suggestion. What do you think @MildTomato?
love it. lets do it 😄

**Comment by ankitjena** [comment]
@phamhieu @MildTomato  I can look into this issue if it's available/not being worked on

**Comment by phamhieu** [comment]
@ankitjena that will be great. Thank you.

**Comment by ankitjena** [comment]
@phamhieu Created the PR
