### ISSUE TITLE
Menu slide animation buggy

### ISSUE THREAD

**Issue by Olyno** [supabase/grid#43]
# Bug report

## Describe the bug

The right menu does not have a clean animation. It have a 2 times animations, which make it not smoothy.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Simply click on "New Column" to get it

## Expected behavior

The animation should be in 1 time to make it smoother and good to see.

## Screenshots

![https://imgur.com/gNDeREl.gif](https://imgur.com/gNDeREl.gif)

## System information

- OS: Linux Debian Deepin
- Browser (if applies) Vivaldi (chromium based) and Chrome
- Version of supabase-js: /
- Version of Node.js: v14.16.1

**Comment by MildTomato** [comment]
Hey @Olyno 👋  - thanks for reporting this

We've just fixed this, and hopefully it'll be released today.

**Comment by phamhieu** [comment]
Dashboard app is deployed!
