### ISSUE TITLE
Clicking on foreign key column should show record details from other table

### ISSUE THREAD

**Issue by emschwartz** [supabase/grid#49]
# Feature request

## Is your feature request related to a problem? Please describe.

A couple of weeks ago, clicking on the arrow+box icon in a cell of a column with a foreign key relation would bring up a side panel with more details of the record in the other table.
![image](https://user-images.githubusercontent.com/3262610/121538416-c2982c80-c9d2-11eb-8606-b2d8e1e91741.png)

Now, it brings up a modal that lets you search through the other table, but it does not show more information about the specific record you clicked on.

## Describe the solution you'd like

It would be nice to be able to quickly see the full details of the record in the other table corresponding to the specific key you click. This could be with the old side panel view, or it might also work to automatically filter the records in the search modal that pops up now.

## Additional context

This experience is currently made worse by the fact that you cannot select and copy the text from a cell with a foreign key relation (or at least not one that's of type `uuid`), so you can't even copy the value and paste it into the search modal.

**Comment by phamhieu** [comment]
Hi @emschwartz We've just fixed this. There' 2 changes in the foreign-key modal:
- show the current selected item detail.
- clear value action will be inside the modal.

hopefully it'll be released to dashboard app soon.

<img width="621" alt="Screenshot 2021-06-11 at 8 34 08 AM" src="https://user-images.githubusercontent.com/689843/121617754-d05fb780-ca8f-11eb-902f-916dcabb388a.png">

**Comment by phamhieu** [comment]
> This experience is currently made worse by the fact that you cannot select and copy the text from a cell with a foreign key relation

For the upcoming update, you can
- `Ctr+c` on a cell to copy the content. 
- right click on a cell to copy

<img width="336" alt="Screenshot 2021-06-11 at 8 41 43 AM" src="https://user-images.githubusercontent.com/689843/121618403-e28e2580-ca90-11eb-81f7-d81e1b1804b8.png">

**Comment by emschwartz** [comment]
Excellent!

**Comment by maximousblk** [comment]
a solution similar to [prisma studio](https://www.prisma.io/studio) (have a separate column) is more optimal imo

![image](https://user-images.githubusercontent.com/28438021/121785057-399d1300-cbd5-11eb-91ab-b71907decdd1.png)

**Comment by phamhieu** [comment]
Thanks @maximousblk, we will look into the suggestions on future update.
