### ISSUE TITLE
Improve text editing

### ISSUE THREAD

**Issue by awalias** [supabase/grid#55]
after editing a record of type `text` I intuitively hit `enter`(return) to save the changes but it adds a new line

![image](https://user-images.githubusercontent.com/458736/122894089-7b6a4e00-d379-11eb-9888-1939e2997add.png)

two potential improvements that come to mind are:

- add a mouse clickable ☑️ icon either inside or outside the text box to save and close the editor
- or make `enter` = save and close, and move the new line = `shift + enter` (although I realize this is already used as a shortcut to add new row)

**Comment by phamhieu** [comment]
we follow airtable. `Enter` will go to new line. `Escape` will save and close the editor.
