### ISSUE TITLE
Refresh Button in the Tables DashBoard

### ISSUE THREAD

**Issue by SamJeffrey8** [supabase/grid#62]
# Feature request

## MongoDB atlas like Database refresh buton

MongoDb atlas has a button to refresh the database wihtout refreshing the whole site, it is not there in firebase but it would be amazing if supabase had it. 

I wish you update this feature soon. Thank you..

**Comment by SamJeffrey8** [comment]
Thanks 🙏
Supabase 🚀🚀🚀

**Comment by phamhieu** [comment]
@SamJeffrey8 can you give some use-cases for this refresh button? 

like you want to refresh the table structure, or just the rows data or maybe both

**Comment by SamJeffrey8** [comment]
Hi @phamhieu , 

Yeah I want both, like when I want to check if new data is inserted in the tables I have to ways to do it now
1. Going to a different table and coming back to the table I want to check, as it reloads thr table alone after I do it without reloading the whole site. This one takes to clicks.
2. Refreshing the whole site and all the components reload along with the table which is a inconvenient way. This one takes one click but a higher loading time than the first one since all the components are reloaded along with the table. 

This refresh button will help supabase users to reload the table alone with just one click. It is very similar to the MongoDB Atlas.

**Comment by phamhieu** [comment]
fixed and deployed
