### ISSUE TITLE
Issue with Supabase Grid and Next.js

### ISSUE THREAD

**Issue by Etheonor** [supabase/grid#66]
Don't know if it's a bug or an issue with my implementation...

I'm trying to use Supabase Grid with Next.js on a SSR page but without any success right now. 

I keep having this error : 
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ForwardRef(LoadableComponent)`.

I also tried to import the module with next/dynamic but doesn't work either... 

Here is the gist of the page I'm trying to render: https://gist.github.com/Etheonor/afc0b12a86e75e8b25a741916e4c9830

Thank you

**Comment by phamhieu** [comment]
Hi @Etheonor, @supabase/grid doesn't have a default export. You need to use named export.

```
const SupabaseGrid = dynamic(() =>
  import("@supabase/grid").then((mod) => mod.SupabaseGrid)
);
```
<img width="1354" alt="Screenshot 2021-07-12 at 8 52 38 AM" src="https://user-images.githubusercontent.com/689843/125219176-94b64880-e2ee-11eb-8939-25e52077ef1f.png">

**Comment by Etheonor** [comment]
Hello and thank you for your answer!

That's weird, I copy/paste your codesandbox page and I got this error 

![image](https://user-images.githubusercontent.com/35852770/125263165-17490300-e303-11eb-989b-d458487b4678.png)

Don't know why... maybe an issue with my other packages?
