### ISSUE TITLE
Cannot modify rows in dashboard table editor when using composite primary key

### ISSUE THREAD

**Issue by officiallymarky** [supabase/grid#73]
# Bug report

Cannot modify rows in dashboard table editor when using composite primary key

## Describe the bug

When using composite primary key, I get an error "can't find primary key" when trying to edit in the table editor.  This is the same error when you have a table with no primary key.

## To Reproduce

Create a composite primary key and try to edit in dashboard table editor

## Expected behavior

The ability to edit rows that use a composite primary key

**Comment by phamhieu** [comment]
@officiallymarky, the new grid should support composite primary key. If you are still facing this problem then kindly let us know the steps to reproduce the bug.
