### ISSUE TITLE
docs: Editable Grid local / development setup

### ISSUE THREAD

**Issue by i-pip** [supabase/grid#80]
# Improve documentation

It's currently not clear how to display the grid with the `editable` prop set to `true`. 

## Describe the problem

What I've tried so far. 
1. Created table [functions](https://github.com/supabase/grid/blob/develop/FUNCTIONS.md) required by `editable` Grid  (Noticed that these are all created in the `auth` schema
2. Added `editable` prop to `SupabaseGrid` component.
2. Added `schema='auth'` to `SupabaseGrid` component - default is public which results in table functions not being found, however setting `schema='auth'` results in error 406 "The schema must be one of the following: public, storage" 
3. Used `SUPABASE_SERVICE_KEY` as `supabaseKey` in `clientProps` - still no joy 

## Describe the improvement

Clear steps for using @supabase/grid in editable mode

**Comment by phamhieu** [comment]
> "The schema must be one of the following: public, storage"

supabase-grid depends on postgREST which currently only access public and storage schema. So if you create helper functions under `auth` schema, unfortunately it will not work.

**Comment by i-pip** [comment]
Got it! thanks @phamhieu - for some reason when I ran the sql to create the helper functions, the default schema was set to auth, not sure if it's my tooling doing this. Explicitly setting `search_path` to public just above the `create function` statements did the trick for me. Is it okay if I add this in the README.md as an additional _Run example_?
