### ISSUE TITLE
[bug] `timestamp` behaves like `timestampz` -  includes timezone when editing

### ISSUE THREAD

**Issue by MildTomato** [supabase/grid#82]
# Bug report

## Describe the bug

timezone is being added to timestamp data

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

https://user-images.githubusercontent.com/8291514/131619696-479bfc44-4a60-4184-be7e-7d2acdf25bc8.mov

## Expected behavior

Should it be no timezone for `timestamp` ?

**Comment by phamhieu** [comment]
fixed: https://github.com/supabase/grid/commit/f172687f6fe1f519212f4c88559e2e5e595f8018, https://github.com/supabase/grid/commit/1f22bd039f5803ad6029016345b7c4f04320fecf
