### ISSUE TITLE
Floating Values doesn't show full value (float8)

### ISSUE THREAD

**Issue by sandbox-apps** [supabase/grid#86]
# Bug report
Example
Actual Value: 0.6000000000000001
Displayed Value: 0.6

**Comment by phamhieu** [comment]
hi @sandbox-apps, float8 supports `15 decimal digits precision`. https://www.postgresql.org/docs/9.1/datatype-numeric.html

However your number has 16 digits precision so the last one is omitted which result in 0.600000000000000 == 0.6
