### ISSUE TITLE
Cannot update table when `identity_generation` set to `ALWAYS` 

### ISSUE THREAD

**Issue by pkoenig10** [supabase/grid#94]
# Bug report

## Describe the bug

The table editor does not allow updating a table that contains a row with `identity_generation` set to `ALWAYS`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table with a `GENERATED ALWAYS AS IDENTITY` row.

    ```sql
    CREATE TABLE data (
        id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        value text NOT NULL
    );
    ```

2. Open this table in the table editor.
3. Attempt to update the value in another column. This results in the following error:

    ```json
    {
        "error": {
            "code": 400,
            "message": "column \"id\" can only be updated to DEFAULT",
            "requestId": "96864405-16a2-403d-9ccd-e4c33642a9c3"
        }
    }
    ```

## Expected behavior

Attempts to update a table that contains a row with `identity_generation` set to `ALWAYS` should be successful if the update does not modify the value in the generated row.

**Comment by phamhieu** [comment]
Fixed on latest deployment
