### ISSUE TITLE
I wish to pass a parameter to populate filter

### ISSUE THREAD

**Issue by johndpope** [supabase/grid#95]
# Feature request

eg. here I'm saying id =1234 

<img width="443" alt="Screen Shot 2021-11-20 at 10 07 29 pm" src="https://user-images.githubusercontent.com/289994/142724235-3ca240cc-fa12-4923-86ed-27ad4a6d67cc.png">

## Describe the solution you'd like

some kind of props / accepting a filter 

UPDATE
digging into the code - seems like the 
```typescript
SavedState which has the filter out of the box may accommodate. 

export interface Filter {
  column: string;
  operator: FilterOperator;
  value: string;
}
```
I'll have to do some more digging on how to use it.

there's this
  storageRef="dqofwyqljsmbgrubmnzk"

maybe I could pass this in here before i use the component to predefine things?
    function saveStorage(state: InitialStateType, storageRef: string) 

still a bit cryptic on how to do this..

```typescript



import React from 'react';
import { SupabaseGrid, SupabaseGridRef, SupaRow } from '@supabase/grid';
import  {saveStorage } from '@supabase/grid/src/SupabaseGrid.utils';
import FilterReducer, {
  FilterInitialState,
  filterInitialState,
} from '@supabase/grid/src/store/reducers/filter';
import { Filter } from '../../src/types';
import {
  initialState
} from '@supabase/grid/src/store/reducers';

  var filters: Filter[] = [];
  function filter(column: string, operator: FilterOperator, value: string) {
    filters.push({ column, operator, value });

  }



  var storageRef="dqofwyqljsmbgrubmnzk";
  filter('name', '=', 'hello world');
  initialState.filters = filters;
  saveStorage(initialState,storageRef=storageRef);


```

APPROACH 2 - 
OK - it seems that I can just hot wire the filters using dispatch???
```typescript

  var filters: Filter[] = [];
  function filter(column: string, operator: FilterOperator, value: string) {
    filters.push({ column, operator, value });

  }
  filter('name', '=', 'hello world');

  dispatch({
    type: 'SET_FILTERS',
    payload: filters,
  });


```

I'll have a go at using this..
![Screen Shot 2021-11-25 at 11 58 52 am](https://user-images.githubusercontent.com/289994/143333600-9c76c952-f575-49b6-b472-f5c6c3df1238.png)

may have to expose a method to pass into this reducer function.....????
@phamhieu - help

APPROACH 3
want to be able to predefine filters here
<img width="379" alt="Screen Shot 2021-11-25 at 12 02 48 pm" src="https://user-images.githubusercontent.com/289994/143333830-67ed0d95-8c90-4097-9c00-20dca9982f11.png">

```typescript

export interface SupabaseGridProps {
    /**
     * database table swagger or table name
     */
    table: SupaTable | string;
    /**
   * predefine filters 
   */
   filters?: Filter[];

```
progressing...
<img width="356" alt="Screen Shot 2021-11-25 at 12 07 22 pm" src="https://user-images.githubusercontent.com/289994/143334116-fb2515d7-7c07-4be5-9ad2-f40e3a23f2dd.png">

```typescript


export function initTable(
  props: SupabaseGridProps,
  state: InitialStateType,
  dispatch: (value: any) => void
) {
  function onInitTable(table: SupaTable, props: SupabaseGridProps) {
    const gridColumns = getGridColumns(table, {
      editable: props.editable,
      defaultWidth: props.gridProps?.defaultColumnWidth,
      onAddColumn: props.editable ? props.onAddColumn : undefined,
    });

    let savedState;
    if (props.storageRef) {
      savedState = onLoadStorage(props.storageRef, table.name, table.schema);
    }

// NEW STUFF HERE....
    if (props.filters) {
      initialState.filters = props.filters;
    }
```

approach 4
<img width="513" alt="Screen Shot 2021-11-25 at 2 25 52 pm" src="https://user-images.githubusercontent.com/289994/143374558-89c4bf88-ec81-46a4-9ccc-4a472e50c088.png">

in sample code
    if (gridRef.current) gridRef.current.addFilter(1,filters[0]);

![Screen Shot 2021-11-25 at 2 25 22 pm](https://user-images.githubusercontent.com/289994/143374594-733ea415-c85d-4d10-9e07-52fa46ea0b8f.png)

don't know why this blows up.... function is here....

<img width="573" alt="Screen Shot 2021-11-25 at 2 26 44 pm" src="https://user-images.githubusercontent.com/289994/143374650-a8688272-f89b-48ac-ad47-2e09fce90869.png">

I can't log with console either...
will keep on digging.

APPROACH 5
```typescript

onSqlQuery={async (query: string) => {
              console.log('query:',query);
              
              // console.log('SupabaseGrid.propTypes:',SupabaseGrid.propTypes);
              // console.log('SupabaseGrid.props:',this.prop);
              
              // var strQuery = "select count(*) from public.transactions where account_id = 258;";;
              console.log("gridProps:",self);
              if (query.includes("select * from public.transactions order by id asc nulls last limit 100 offset 0;")){
                query = "select * from public.transactions where account_id = 258 order by id asc nulls last limit 100 offset 0; "
              }
              const res = await postAndWait('/api/sql-query', { query });
              console.log("res:",res);
              return res;
            }}

here I just hack the sql query by intercepting the call - it's too fragile....but working.
```

**Comment by johndpope** [comment]
@phamhieu - from 5 approaches above - is there any preference you have in mind?

**Comment by phamhieu** [comment]
APPROACH 3 sounds good to me
- provide a default filters
  - if the filters from savedState is empty, populate it with default filters
  - else use filters from savedState

**Comment by johndpope** [comment]
drafted - https://github.com/johndpope/grid

it's misbehaving a tiny bit as I can't remove the filter.

**Comment by johndpope** [comment]
I think I need to recognise the filters / load them and save / persist to disk / but then discard them. Sounds a bit convoluted but can’t see any other way to avoid above bugs.

**Comment by johndpope** [comment]
so I think I'm close - I pushed this branch  https://github.com/johndpope/grid/tree/dist

it's using approach 4 - and hooks into the React.useImperativeHandle
```typescript
export interface SupabaseGridRef {
  /**
   * callback when a new row is added
   *
   * @param row   newly added row data
   */
  rowAdded(row: Dictionary<any>): void;
  /**
   * callback when a row is edited
   *
   * @param row   edited row data
   * @param idx   edited row index
   */
  rowEdited(row: Dictionary<any>, idx: number): void;
  updateFilter(filterIdx: number, filter: Filter): void;
  addFilter(theFilter: Filter): void;
  removeFilter(filterIdx: number): void;
  getTheFilters():Filter[];
}

```

I can wait for page to load - then inject the filter at some point - 
but now I need to return all the filters.

When I attempt to return 

const SupabaseGridLayout = React.forwardRef<SupabaseGridRef, SupabaseGridProps>(
  (props, ref) => {
    const { editable, storageRef, gridProps, headerActions } = props;
    const dispatch = useDispatch();
    const state = useTrackedState();
    const gridRef = React.useRef<DataGridHandle>(null);
    const [mounted, setMount] = React.useState(false);


    React.useImperativeHandle(ref, () => ({

      getTheFilters(){
        console.log("⛳️  getTheFilters");
        return state.filters;
      },

I get a proxy back - not the actual filters.....


any ideas ????
