### ISSUE TITLE
it seems like this code is really using the pool - just creating new ones each time...

### ISSUE THREAD

**Issue by johndpope** [supabase/grid#98]
https://github.com/supabase/grid/blob/e216168b5a35d9dedc812f3917cdcfa886e05d09/example/pages/api/sql-query.ts#L10

I have some other sample code that creates a const pool - that way the pool is reused..

// node-pg returns numerics as strings by default. since we don't expect to
// have large currency values, we'll parse them as floats instead.
types.setTypeParser(1700, val => parseFloat(val));

// These environment variables are set in the repo root's docker-compose.yml
const { DB_PORT, DB_HOST_NAME, POSTGRES_USER, POSTGRES_PASSWORD } = process.env;

// Create a connection pool. This generates new connections for every request.
const db = new Pool({
  host: DB_HOST_NAME,
  port: DB_PORT,
  user: POSTGRES_USER,
  password: POSTGRES_PASSWORD,
  max: 5,
  min: 2,
  idleTimeoutMillis: 1000, // close idle clients after 1 second
  connectionTimeoutMillis: 1000, // return an error after 1 second if connection could not be established
});

module.exports = db;

**Comment by johndpope** [comment]
I see you shut it down at the bottom - but wouldn't it be better to keep the pool around?

**Comment by phamhieu** [comment]
It's ok for an example app. 

For prod app, Yes you should keep the pool connection and reused it for better performance.
